name: CI

on:
  workflow_dispatch:
  
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: windows-2022
    #runs-on: windows-2019
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Build Kernel Isolator x64
        run: msbuild /t:build ProcessHacker\KSystemInformer\KSystemInformer.sln /p:Configuration="Release" /p:Platform=x64
        
      - name: Build Kernel Isolator arm64
        run: msbuild /t:build ProcessHacker\KSystemInformer\KSystemInformer.sln /p:Configuration="Release" /p:Platform=ARM64

      - name: Upload Build
        uses: actions/upload-artifact@v4.4.3
        with:
          name: KSystemInformer_x64
          path: |
            ProcessHacker/KSystemInformer/bin/Release64/*.sys
            ProcessHacker/KSystemInformer/bin/Release64/*.pdb
            
      - name: Upload Build
        uses: actions/upload-artifact@v4.4.3
        with:
          name: KSystemInformer_ARM64
          path: |
            ProcessHacker/KSystemInformer/bin/ReleaseARM64/*.sys
            ProcessHacker/KSystemInformer/bin/ReleaseARM64/*.pdb
